#!/usr/bin/env python
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Ioannis Valasakis <tungolcild@gmail.com>
"""Regenerate the shipped corpus definition artifacts from ``artefaux.corpus``.

Writes ``recipes/corpus.yaml`` (the authoritative record specs) and the
authored ``manifest.json`` / ``manifest.csv`` (index of the corpus — every field
here is determined by the specs, independent of the source signals). These are the
metadata artifacts the repository ships; the WFDB signals are regenerated by users
with ``make regenerate``.
"""

from __future__ import annotations

from pathlib import Path

from artefaux.corpus import build_corpus_specs, specs_to_yaml
from artefaux.manifest import Manifest, ManifestEntry
from artefaux.recipes import build_record
from artefaux.synthetic import synthetic_parent_signal

MASTER_SEED = 20260713


def main() -> int:
    repo = Path(__file__).resolve().parents[1]
    specs = build_corpus_specs()

    (repo / "recipes").mkdir(exist_ok=True)
    (repo / "recipes" / "corpus.yaml").write_text(specs_to_yaml(specs, MASTER_SEED))

    manifest = Manifest()
    for spec in specs:
        # A synthetic parent suffices: every manifest column is authored from the
        # spec, not measured from the signal.
        parent = synthetic_parent_signal(seed=spec.seed_index)
        _, label = build_record(parent, spec, MASTER_SEED, fs=500)
        parent_id = f"{spec.record_id}_clean" if spec.has_clean_parent else None
        manifest.add(ManifestEntry.from_label(label, parent_record_id=parent_id))

    manifest.write_json(repo / "manifest.json")
    manifest.write_csv(repo / "manifest.csv")
    print(
        f"Wrote recipes/corpus.yaml, manifest.json, manifest.csv "
        f"({len(specs)} records: {manifest.counts_by_group()})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
